server:
  port: 8080
  servlet:
    context-path: /
    session:
      tracking-modes: cookie
  compression:
    enabled: true
    mime-types: application/json

spring:
  redis:
    # 地址
    host: 10.3.70.211    # 119.91.231.160
    # 端口，默认为6379
    port: 6379
    # 密码
    password: "DCone7888#"   # "000415"
    # 连接超时时间
    timeout: 100s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    database: 2
  #mysql配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # Mysql数据库驱动包
    url: jdbc:mysql://119.91.231.160:3306/ai-yixuan?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: tj199911

#    druid:
#      max-active: 100
#      initial-size: 20
#      min-idle: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      validation-query: SELECT 1 from dual
#      validation-query-timeout: 1000
#      keep-alive: true
#      remove-abandoned: true
#      remove-abandoned-timeout: 180
#      log-abandoned: true
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      filters: stat,slf4j
#      use-global-data-source-stat: true
#      preparedStatement: true
#      maxOpenPreparedStatements: 100
#      connect-properties:
#        mergeSql: true
#        slowSqlMillis: 5000






